<?php

namespace Skywatch\Laravel\Commands;

use Skywatch\Laravel\SkywatchClient;
use Illuminate\Console\Command;
use RuntimeException;
use Throwable;

class TestSkywatchCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'skywatch:ping';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Send a single test exception to the Skywatch hub (SDK smoke test)';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $dsn = config('skywatch.dsn') ?: env('SKYWATCH_DSN', env('EXCEPTION_TRACKER_DSN'));
        $key = config('skywatch.key') ?: env('SKYWATCH_KEY', env('EXCEPTION_TRACKER_KEY'));

        $this->info('Testing Skywatch Integration...');
        $this->line('DSN: '.($dsn ?: 'Not Configured'));
        $this->line('Key: '.($key ? substr($key, 0, 15).'...' : 'Not Configured'));

        if (! $dsn || ! $key) {
            $this->error('Failed: SKYWATCH_DSN and SKYWATCH_KEY must be set in your .env file.');

            return 1;
        }

        try {
            $client = new SkywatchClient;

            // Generate a test exception
            $exception = new RuntimeException('This is a test exception generated by php artisan skywatch:ping.');

            $client->capture($exception);

            $this->info('Success: A test exception has been captured and transmitted to the hub.');

            return 0;
        } catch (Throwable $e) {
            $this->error('Failed to capture test exception: '.$e->getMessage());

            return 1;
        }
    }
}
