<?php

namespace FaultScope\Laravel\Commands;

use FaultScope\Laravel\FaultScopeClient;
use Illuminate\Console\Command;
use RuntimeException;
use Throwable;

class TestFaultScopeCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'faultscope:ping';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Send a single test exception to the FaultScope hub (SDK smoke test)';

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $dsn = config('faultscope.dsn') ?: env('FAULTSCOPE_DSN', env('FAULTSCOPE_DSN'));
        $key = config('faultscope.key') ?: env('FAULTSCOPE_KEY', env('FAULTSCOPE_KEY'));

        $this->info('Testing FaultScope Integration...');
        $this->line('DSN: '.($dsn ?: 'Not Configured'));
        $this->line('Key: '.($key ? substr($key, 0, 15).'...' : 'Not Configured'));

        if (! $dsn || ! $key) {
            $this->error('Failed: FAULTSCOPE_DSN and FAULTSCOPE_KEY must be set in your .env file.');

            return 1;
        }

        try {
            $client = new FaultScopeClient;

            // Generate a test exception
            $exception = new RuntimeException('This is a test exception generated by php artisan faultscope:ping.');

            $client->capture($exception);

            $this->info('Success: A test exception has been captured and transmitted to the hub.');

            return 0;
        } catch (Throwable $e) {
            $this->error('Failed to capture test exception: '.$e->getMessage());

            return 1;
        }
    }
}
